### ISSUE TITLE
get_section_heatmap returning no results

### ISSUE THREAD

**Issue by kaimikacolin** [oceanproteinportal/api#16]
Mak reports: "Trying out the https://opp-test.whoi.edu/# KG version, exciting! Looking really good so far.
Noticed this error on some section plots "An the following error occurred while attempting to render the plot:
min() arg is an empty sequence" For example search iron, first section works but next bunch do not, all of them are ProteOMZ dataset." 

Here's the underlying query that is returning no results:
https://kg.oceanproteinportal.org/?query=SELECT+DISTINCT+STR%28%3Fdepth%29+AS+%3Fdepth+%3Fstation+STR%28%3FspectralCount%29+AS+%3FspectralCount%0D%0A++++++++WHERE+%0D%0A++++++++%7B+%3Curn%3Aopp%3Adataset%3Aproteomz%3E+opp%3AstoresResultsForSample+%3Fsample+.%0D%0A++++++++++++%3Fsample+sosa%3AisSampleOf+%3Ffeature+.%0D%0A++++++++++++%3Ffeature+opp%3Adepth+%3Fdepth+.%0D%0A++++++++++++%3Ffeature+opp%3AinVicinityOfStation+%3FstationInfo+.%0D%0A++++++++++++%3FstationInfo+opp%3AstationName+%3Fstation+.+%09+%0D%0A++++++++++++%3Fobservation+opp%3AobservationInSample+%3Fsample+.%0D%0A++++++++++++%3Fobservation+schema%3Avalue+%3FspectralCount+.+%0D%0A++++++++++++%3Fobservation+rdf%3Atype+opp%3AProteinTotalSpectralCount+.%0D%0A++++++++++++%3Fprotein+opp%3AsampleProteinProperty+%3Fobservation+.%0D%0A++++++++++++%3Fprotein+opp%3AproteinIdentifier+%22NODE_84_length_55275_cov_34.8928_47984_50596_+%22%5E%5Exsd%3Atoken+.%0D%0A++++++++%7D%0D%0A++++++++ORDER+BY+%3Fstation%0D%0A

Let me know if there's a different way we should handle these failures

**Comment by kaimikacolin** [comment]
@jaclynsaunders @ashepherd

**Comment by jaclynsaunders** [comment]
I believe this has been solved, so closing this issue
