### ISSUE TITLE
Missing Data on new Instance

### ISSUE THREAD

**Issue by kaimikacolin** [oceanproteinportal/api#19]
In switching over to the new endpoint, I've noticed that this data seems to be missing:

[Cruises Datasets Filters Query](http://pp-kg.whoi.edu:7200/sparql?name=Protein%20Search&infer=true&sameAs=true&query=PREFIX%20view:%20%3Chttp:%2F%2Fschema.oceanproteinportal.org%2Fv2%2Fviews%2F%3E%0APREFIX%20opp:%20%3Chttp:%2F%2Fschema.oceanproteinportal.org%2Fv2%2F%3E%0APREFIX%20sosa:%20%3Chttp:%2F%2Fwww.w3.org%2Fns%2Fsosa%2F%3E%0APREFIX%20xsd:%20%3Chttp:%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0APREFIX%20onto:%20%3Chttp:%2F%2Fwww.ontotext.com%2F%3E%0APREFIX%20schema:%20%3Chttp:%2F%2Fschema.org%2F%3E%0APREFIX%20v2:%20%3Chttp:%2F%2Fschema.oceanproteinportal.org%2Fv2%2F%3E%0ASELECT%20*%0A%20%20%20%20%20%20%20%20WHERE%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20GRAPH%20%3Curn:opp:statistics%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Curn:opp:statistics%3E%20view:allCruises%20%3Fcruises_json%20.%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Curn:opp:statistics%3E%20view:allDatasets%20%3Fdatasets_json%20.%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Curn:opp:statistics%3E%20view:allFilterSizes%20%3Ffilters_json%20.%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%20%0A)

**Comment by jaclynsaunders** [comment]
@kaimikacolin @ashepherd - so from what I can tell, the views were generated (based upon [the rdf generator repo](https://github.com/oceanproteinportal/rdf-generator/blob/main/code/rdf-generate/total-spectral-counts/opp-views/app.py) However, I'm not finding the graph named <urn:opp:statistics>.
