### ISSUE TITLE
SPARQL query - models.py:21 - find_peptides_by_protein_id

### ISSUE THREAD

**Issue by sanjaygovindarajan** [oceanproteinportal/api#2]
### models.py:21
**param input:** ProteinID
**returns:** peptideSequence
```
SELECT DISTINCT ?peptideSequence
WHERE 
  { ?protein opp:proteinIdentifier "NODE_2665_length_10184_cov_5.78873_5105_6295_-"^^xsd:token . 
    ?pip opp:forProteinIdentification ?protein .
    ?identifier opp:suggestsProtein ?pip .
    ?identifier opp:describesPeptide ?peptide.
    ?peptide opp:peptideSequence ?peptideSequence .
}
```
[Snorql OPP query](https://kg.oceanproteinportal.org/?query=SELECT+DISTINCT+%3FpeptideSequence%0D%0AWHERE+%0D%0A++%7B+%3Fprotein+opp%3AproteinIdentifier+%22NODE_2665_length_10184_cov_5.78873_5105_6295_-%22%5E%5Exsd%3Atoken+.+%0D%0A++++%3Fpip+opp%3AforProteinIdentification+%3Fprotein+.%0D%0A++++%3Fidentifier+opp%3AsuggestsProtein+%3Fpip+.%0D%0A++++%3Fidentifier+opp%3AdescribesPeptide+%3Fpeptide.%0D%0A++++%3Fpeptide+opp%3ApeptideSequence+%3FpeptideSequence+.%0D%0A%7D)

Note: This query includes the protein id ```NODE_2665_length_10184_cov_5.78873_5105_6295_-``` as an example parameter.

**Comment by kaimikacolin** [comment]
Turns out this method was not used in the code base at all. This can be closed.
