### ISSUE TITLE
SPARQL query - models.py:47 - get_static_data__cruises

### ISSUE THREAD

**Issue by sanjaygovindarajan** [oceanproteinportal/api#5]
### models.py:47
get_static_data__cruises.json
params: none
returns: array of cruises each containing an array of stations with name, lat/long
cruises_query = {"_source": ["cruises"], "size": 100}

```
SELECT DISTINCT ?cruise (ROUND(?lat * 10) / 10) as ?lat (ROUND(?lon * 10) / 10) as ?lon ?sn ?c
WHERE { 
    ?s opp:sampleFromCruise ?c .
    ?c opp:cruiseID ?cruise .
    ?s sosa:isSampleOf ?foi .
    ?foi geo:lat ?lat .
    ?foi geo:lon ?lon .
    ?foi opp:inVicinityOfStation ?station .
    ?station opp:stationName ?sn .
}
ORDER BY ?c
```
[Snorql OPP query](https://kg.oceanproteinportal.org/?query=SELECT+DISTINCT+%3Fcruise+%28ROUND%28%3Flat+*+10%29+%2F+10%29+as+%3Flat+%28ROUND%28%3Flon+*+10%29+%2F+10%29+as+%3Flon+%3Fsn+%3Fc%0D%0AWHERE+%7B+%0D%0A++++%3Fs+opp%3AsampleFromCruise+%3Fc+.%0D%0A++++%3Fc+opp%3AcruiseID+%3Fcruise+.%0D%0A++++%3Fs+sosa%3AisSampleOf+%3Ffoi+.%0D%0A++++%3Ffoi+geo%3Alat+%3Flat+.%0D%0A++++%3Ffoi+geo%3Alon+%3Flon+.%0D%0A++++%3Ffoi+opp%3AinVicinityOfStation+%3Fstation+.%0D%0A++++%3Fstation+opp%3AstationName+%3Fsn+.%0D%0A%7D%0D%0AORDER+BY+%3Fc)

Note: This query rounds to remove duplicates. Even with rounding, there appears to still be one duplicate. This feature can easily be removed if necessary. It also does not sort by database, although this can be added if necessary.

**Comment by kaimikacolin** [comment]
This has been implemented and looks great.

**Comment by jaclynsaunders** [comment]
@kaimikacolin - should we close this issue?

**Comment by kaimikacolin** [comment]
Yup!
