### ISSUE TITLE
SPARQL query - models.py:22 - get_static_data.json

### ISSUE THREAD

**Issue by sanjaygovindarajan** [oceanproteinportal/api#6]
### models.py:22
get_static_data.json
params: none
returns discrete values:
depth.min, depth.max, filterSize.min, filterSize.max and an array of filter sizes for the UI dropdown

```
SELECT DISTINCT MAX(?depth) as ?max_depth MIN(?depth) as ?min_depth MIN(?minfs) as ?minfs MAX(?maxfs) as ?maxfs
WHERE {
  VALUES ?graph { <urn:opp:graph:metzyme-0.2> }
  GRAPH ?graph {
  ?foi rdf:type sosa:FeatureOfInterest . 
  ?foi opp:depth ?depth .
  ?sampler rdf:type sosa:Sampler .
  ?sampler opp:hasFilterSize ?fs .
  ?fs opp:minimumFilterSize ?minfs .
  ?fs opp:maximumFilterSize ?maxfs .
}}
```
[Snorql OPP query](https://kg.oceanproteinportal.org/?query=SELECT+DISTINCT+MAX%28%3Fdepth%29+as+%3Fmax_depth+MIN%28%3Fdepth%29+as+%3Fmin_depth+MIN%28%3Fminfs%29+as+%3Fminfs+MAX%28%3Fmaxfs%29+as+%3Fmaxfs%0D%0AWHERE+%7B%0D%0A++VALUES+%3Fgraph+%7B+%3Curn%3Aopp%3Agraph%3Ametzyme-0.2%3E+%7D%0D%0A++GRAPH+%3Fgraph+%7B%0D%0A++%3Ffoi+rdf%3Atype+sosa%3AFeatureOfInterest+.+%0D%0A++%3Ffoi+opp%3Adepth+%3Fdepth+.%0D%0A++%3Fsampler+rdf%3Atype+sosa%3ASampler+.%0D%0A++%3Fsampler+opp%3AhasFilterSize+%3Ffs+.%0D%0A++%3Ffs+opp%3AminimumFilterSize+%3Fminfs+.%0D%0A++%3Ffs+opp%3AmaximumFilterSize+%3Fmaxfs+.%0D%0A%7D%7D)

Note: I assumed that I should sort by database because that is how the data is used on the OPP website, but it can be changed if needed. The query uses metzyme-0.2 as an example value for the database parameter, but it can be any database or even multiple databases.

**Comment by kaimikacolin** [comment]
This has been implemented! Need to discuss what effect these values should have on the front-end search.

**Comment by jaclynsaunders** [comment]
@kaimikacolin - should we close this issue?

**Comment by kaimikacolin** [comment]
Yup! Would it be possible to grant me admin priv so I can have that control over these issues?

**Comment by jaclynsaunders** [comment]
Yup! Just gave you admin priv
