### ISSUE TITLE
Peptides missing from Query?

### ISSUE THREAD

**Issue by kaimikacolin** [oceanproteinportal/api#7]
@jaclynsaunders This query provides a "peptideCount" but no peptides... is there any way this can be included per-result as an array?

https://kg.oceanproteinportal.org/?query=+SELECT+DISTINCT+%3Fprotein+%3Fproduct_name+%3Fdataset+%3Fdataset_name+%3Fexpedition+%3Fspectral_count+%3Fprotein_id+%3Fpeptide_count+%3Fsequence+%3Fids%0D%0A++++++++WHERE+%7B+%0D%0A++++++++%3Fprotein+a+%3Chttp%3A%2F%2Fschema.oceanproteinportal.org%2Fv2%2Fviews%2FProteinFound%3E+.%0D%0A++++++++%3Fprotein+%3Fp+%3Fo+.%0D%0A++++++++FILTER+REGEX%28%3Fo%2C+%22FE%22%2C+%22i%22%29%0D%0A++++++++%0D%0A++++++++%3Fprotein+view%3AproductName+%3Fproduct_name+.%0D%0A++++++++%3Fprotein+view%3Aidentifiers+%3Fids+.%0D%0A++++++++%3Fprotein+view%3AdatasetName+%3Fdataset_name+.%0D%0A++++++++%3Fprotein+view%3Adataset+%3Fdataset+.%0D%0A++++++++%3Fprotein+view%3Aexpedition+%3Fexpedition+.%0D%0A++++++++%3Fprotein+view%3AspectralCount+%3Fspectral_count+.%0D%0A++++++++%3Fprotein+view%3AproteinID+%3Fprotein_id+.%0D%0A++++++++%3Fprotein+view%3ApeptideCount+%3Fpeptide_count+.%0D%0A++++++++%3Fprotein+view%3Asequence+%3Fsequence+.%0D%0A++++++++%7D%0D%0A++++++++ORDER+BY+DESC%28%3Fspectral_count%29%0D%0A&graph=urn%3Aopp%3Aviews%3Anunn-bering-sea

**Comment by jaclynsaunders** [comment]
@kaimikacolin - do you want basically all the peptides found within a protein along with the spectral counts for those peptides? (I'm also noticing an issue here with the data that we'll need to dig into.) 

For example this protein has spectral count of 212 but peptide count of 0?

> <urn:opp:view:protein-id:162e41ca-102d-3d09-9bad-8b1182c27328> | "Succinate dehydrogenase flavoprotein subunit"^^xsd:string | <urn:opp:dataset:nunn-bering-sea> | "Arctic-Bering Sea (Nunn)"^^xsd:string | "HLY1301"^^xsd:string | 212.0 | "MOCAT.samples_revised_C16119679_gene1_3"^^xsd:token | 0

Let me get back to you on this one, Colin. Thanks!

**Comment by kaimikacolin** [comment]
The ES engine was providing peptides like so: 'peptideSequence': ['GFYDDNYTTSPEK', 'GATDLQAADQEITAVYAQLLHK'] , so I don't think spectral counts are necessary. 

Those values are then sent to this view:
![image](https://user-images.githubusercontent.com/65564591/157135848-45caf9df-e648-43ca-8fe7-bfe14137b33f.png)

**Comment by kaimikacolin** [comment]
Marking this one "medium" priority

**Comment by jaclynsaunders** [comment]
Want to return an array of peptide sequence strings per protein. Return as JSON?

**Comment by kaimikacolin** [comment]
Yes a JSON object would be fine

**Comment by jaclynsaunders** [comment]
@kaimikacolin - Here's a query that can plug into the other protein view queries. [Here's a working example of finding just the peptides per protein - returned as a string with comma-separated values for each peptide.](https://kg.oceanproteinportal.org/?query=SELECT+DISTINCT+%3Fprotein_name+%28GROUP_CONCAT%28DISTINCT%28%3Fpeptide_sequence%29%2C+%27%2C%27%29+AS+%3Fpeptide_list%29%0D%0AWHERE+%7B+%0D%0A%3Fprotein+view%3AviewOf+%3Fprotein_id+.%0D%0A%3Fprotein_id+opp%3AproteinIdentifier+%3Fprotein_name+.%0D%0A%3Fpep_b+opp%3AforProteinIdentification+%3Fprotein_id+.%0D%0A%3Fpeptide_id+opp%3AsuggestsProtein+%3Fpep_b+.%0D%0A%3Fpeptide_id+opp%3AdescribesPeptide+%3Fpep_id+.%0D%0A%3Fpep_id+opp%3ApeptideSequence+%3Fpeptide_sequence+.%0D%0A%7D%0D%0AGROUP+BY+%3Fprotein_name)
```
SELECT DISTINCT ?protein_name (GROUP_CONCAT(DISTINCT(?peptide_sequence), ',') AS ?peptide_list)
WHERE { 
?protein view:viewOf ?protein_id .
?protein_id opp:proteinIdentifier ?protein_name .
?pep_b opp:forProteinIdentification ?protein_id .
?peptide_id opp:suggestsProtein ?pep_b .
?peptide_id opp:describesPeptide ?pep_id .
?pep_id opp:peptideSequence ?peptide_sequence .
}
GROUP BY ?protein_name
```

**Comment by jaclynsaunders** [comment]
@kaimikacolin - [Here's with the peptide list coming from the main query](https://kg.oceanproteinportal.org/?query=++++++++SELECT+DISTINCT+%3Fprotein+%3Fproduct_name+%3Fdataset+%3Fdataset_name+%3Fexpedition+%3Fspectral_count+%3Fprotein_id+%3Fpeptide_count+%3Fsequence+%3Fids+%28GROUP_CONCAT%28DISTINCT%28%3Fpeptide_sequence%29%2C+%27%2C%27%29+AS+%3Fpeptide_list%29%0D%0A++++++++WHERE+%7B%0D%0A++++++++VALUES+%3Fp+%7B+view%3AproductName+view%3Aidentifiers+view%3AproteinID++%7D%0D%0A++++++++%3Fprotein+a+%3Chttp%3A%2F%2Fschema.oceanproteinportal.org%2Fv2%2Fviews%2FProteinFound%3E+.%0D%0A++++++++%0D%0A++++++++FILTER+REGEX%28%3Fo%2C+%22FE%22%2C+%22i%22%29%0D%0A++++++++%3Fprotein+%3Fp+%3Fo+.%0D%0A%0D%0A++++++++%3Fprotein+view%3AproductName+%3Fproduct_name+.%0D%0A++++++++%3Fprotein+view%3Aidentifiers+%3Fids+.%0D%0A++++++++%3Fprotein+view%3AdatasetName+%3Fdataset_name+.%0D%0A++++++++%3Fprotein+view%3Adataset+%3Fdataset+.%0D%0A++++++++%3Fprotein+view%3Aexpedition+%3Fexpedition+.%0D%0A++++++++%3Fprotein+view%3AspectralCount+%3Fspectral_count+.%0D%0A++++++++%3Fprotein+view%3AproteinID+%3Fprotein_id+.%0D%0A++++++++%3Fprotein+view%3ApeptideCount+%3Fpeptide_count+.%0D%0A++++++++%3Fprotein+view%3Asequence+%3Fsequence+.%0D%0A++++++++%3Fprotein+view%3AviewOf+%3Fopp_protein+.%0D%0A++++++++%3Fpep_b+opp%3AforProteinIdentification+%3Fopp_protein+.%0D%0A++++++++%3Fpeptide_id+opp%3AsuggestsProtein+%3Fpep_b+.%0D%0A++++++++%3Fpeptide_id+opp%3AdescribesPeptide+%3Fpep_id+.%0D%0A++++++++%3Fpep_id+opp%3ApeptideSequence+%3Fpeptide_sequence+.%0D%0A++++++++%7D%0D%0A++++++++GROUP+BY+%3Fexpedition+%3Fdataset+%3Fdataset_name+%3Fprotein+%3Fproduct_name+%3Fprotein_id+%3Fspectral_count+%3Fpeptide_count+%3Fsequence+%3Fids%0D%0A++++++++ORDER+BY+DESC%28%3Fspectral_count%29%0D%0A). It would probably be best to have it as a view, but this query works for now. 

[Here it is as a query with filters on depth & date with regex](https://kg.oceanproteinportal.org/?query=SELECT+DISTINCT+%3Fdataset+%3Fdataset_name+%3Fexpedition+%3Fprotein+%3Fproduct_name+%28SUM%28%3Fspectral_counts%29+AS+%3Fspectral_count_sum%29+%3Fids+%3Fprotein_sequence+%28COUNT%28DISTINCT%28%3Fpeptide_sequence%29%29+AS+%3Ftotal_peptides%29+%28GROUP_CONCAT%28DISTINCT%28%3Fpeptide_sequence%29%2C+%27%2C%27%29+AS+%3Fpeptide_list%29%0D%0A%0D%0AWHERE+%7B%0D%0AVALUES+%3Fp+%7B+view%3AproductName+view%3Aidentifiers+view%3AproteinID+%7D%0D%0A%3Fprotein_view+a+%3Chttp%3A%2F%2Fschema.oceanproteinportal.org%2Fv2%2Fviews%2FProteinFound%3E+.%0D%0A++++++++%0D%0AFILTER+REGEX%28%3Fo%2C+%22rubisco%22%2C+%22i%22%29%0D%0A%3Fprotein_view+%3Fp+%3Fo+.%0D%0A%3Fprotein_view+view%3AviewOf+%3Fprotein_id+.%0D%0A%3Fprotein_view+view%3Aidentifiers+%3Fids+.+%0D%0A%3Fprotein_view+view%3Asequence+%3Fprotein_sequence+.+%0D%0A%3Fprotein_view+view%3AproductName+%3Fproduct_name+.%0D%0A%3Fprotein_view+view%3AproteinID+%3Fprotein+.%0D%0A%3Fprotein_view+view%3Adataset+%3Fdataset+.%0D%0A%3Fprotein_view+view%3AdatasetName+%3Fdataset_name+.%0D%0A%3Fprotein_view+view%3Aexpedition+%3Fexpedition+.%0D%0A%3Fdataset+opp%3AstoresResultsForSample+%3Fsample+.%0D%0A%3Fprotein_b+opp%3AobservationInSample+%3Fsample+.%0D%0A%3Fdataset+opp%3AstoresResultsForSample+%3Fsample+.%0D%0A%3Fsample+sosa%3AisSampleOf+%3Fsample_feature+.%0D%0AFILTER+%28%3Fdepth+%3E%3D+50+%26%26+%3Fdepth+%3C%3D+200%29+.%0D%0A%3Fsample_feature+opp%3Adepth+%3Fdepth+.%0D%0A%3Fsample+sosa%3AisResultOf+%3Fsample_event+.%0D%0AFILTER+%28%3Fdate_time+%3E%3D+%222010-01-01%22%5E%5Exsd%3AdateTime+%26%26+%3Fdate_time+%3C%3D+%222022-01-01%22%5E%5Exsd%3AdateTime%29+.%0D%0A%3Fsample_event+sosa%3AresultTime+%3Fdate_time+.%0D%0A%3Fprotein_id+opp%3AsampleProteinProperty+%3Fprotein_b+.%0D%0A%3Fprotein_id+opp%3AproteinIdentifier+%3Fprotein+.%0D%0A%0D%0A%23FILTER+%28%3Fspectral_counts+%3E+0%29+.%0D%0A%3Fprotein_b+schema%3Avalue+%3Fspectral_counts+.%0D%0A%0D%0A%3Fpep_b+opp%3AforProteinIdentification+%3Fprotein_id+.%0D%0A%3Fpeptide_id+opp%3AsuggestsProtein+%3Fpep_b+.%0D%0A%3Fpeptide_id+opp%3AdescribesPeptide+%3Fpep_id+.%0D%0A%3Fpep_id+opp%3ApeptideSequence+%3Fpeptide_sequence+.%0D%0A%7D%0D%0AGROUP+BY+%3Fdataset+%3Fdataset_name+%3Fexpedition+%3Fprotein_id+%3Fprotein+%3Fproduct_name+%3Fids+%3Fprotein_sequence%0D%0A). However, still stuck on filtering out samples where spectral counts = 0
